### ISSUE TITLE
[Bug] TypeError: object null is not iterable (cannot read property Symbol(Symbol.iterator))

### ISSUE THREAD

**Issue by JosXa** [ryu1kn/vscode-remote-repo-viewer#12]
Wondering if there's a regression of #2 or something specific to my environment:
With any https URL I've tried so far I'm running into below exception, for example `https://github.com/ryu1kn/vscode-remote-repo-viewer`, however the ssh+git variants work fine.

```
TypeError: object null is not iterable (cannot read property Symbol(Symbol.iterator))    at Object.directoryName (c:\Users\INT002327\.vscode\extensions\ryu1kn.remote-repo-viewer-0.4.0\lib\repository.config.js:49:30)    at Repository.downloadIfNotExist (c:\Users\INT002327\.vscode\extensions\ryu1kn.remote-repo-viewer-0.4.0\lib\repository.js:15:37)    at OpenRepositoryCommand.execute (c:\Users\INT002327\.vscode\extensions\ryu1kn.remote-repo-viewer-0.4.0\lib\commands\open-repository.js:21:47)    at runMicrotasks (<anonymous>:null:null)    at processTicksAndRejections (internal/process/task_queues.js:94:5)

Command 'RemoteRepoViewer: Open repository in a new window' resulted in an error (object null is not iterable (cannot read property Symbol(Symbol.iterator)))
```

See [this screencast](https://s3.nl-ams.scw.cloud/josxa-content/50/welRuThL1q.mp4) for repro. I am on Windows with VSCode 1.51.1.

**Comment by ryu1kn** [comment]
Hi @JosXa , thanks for reporting this. I could reproduce the problem. Also confirmed that ssh+git works as you wrote.

**Comment by ryu1kn** [comment]
Also, thanks so much for providing the super clear/easy-to-understand screencast!!

**Comment by ryu1kn** [comment]
Strange. I seem to be unable to reproduce the issue anymore. I don't think I did anything other than updating VS Code. Can you see if you can reproduce this issue??

My current VS Code version is 1.52.1.

**Comment by ryu1kn** [comment]
Memo: This is the test that should be confirming this https case

https://github.com/ryu1kn/vscode-remote-repo-viewer/blob/b75a1e5e2d09f49c742d8f2009f965c3b4379aef/test/unit/commands/open-repository.test.js#L31-L47

**Comment by JosXa** [comment]
@ryu1kn With pleasure, I think this project is a great idea :) 

On 1.53.0-insider, I can still reproduce the problem. Edit: Same in 1.52.1 🤔

**Comment by ryu1kn** [comment]
Thanks for the encouraging comment.

I got it. When I first reproduced it, I followed your steps which use `https://github.com/ryu1kn/vscode-remote-repo-viewer` as a repo url.

Then after a while, I used the https url from below, which is actually `https://github.com/ryu1kn/vscode-remote-repo-viewer.git` (note that it ends with `.git`), a clone url, which works fine.

![image](https://user-images.githubusercontent.com/1505715/102708485-ae168980-42f7-11eb-8cb6-b202b0ad3fa4.png)

So actually the page URL is an unsupported URL at the moment. The default (catch-all) rule is agnostic of provider (github/bitbucket/...); so i want to keep it for providing the clone URLs.

Having said that, going to a repo URL and being able to just grab that page URL is easier flow than clicking "Code" button and  clicking the copy-to-clipboard button *after* going to a repo URL.

**Comment by ryu1kn** [comment]
I wonder if we can introduce a new rule for downloading a repo from a given GitHub repo URL (not its clone URL). GitHub already has one rule (prefix `g `) that expects `<org-id>/<repo-name>` (e.g. `g ryu1kn/vscode-remote-repo-viewer`).

I wish `g` were still available for this purpose, and `<org-id>/<repo-name>` were using `gs` (github short name) or something...

`gu` (GitHub URL)?
